// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Ferreus Vault Contributors
//
// This file is part of Ferreus Vault.
//
// Ferreus Vault is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3 only,
// as published by the Free Software Foundation.
//
// Ferreus Vault is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

//! Persistent storage for the device-specific secret key.
//!
//! [`DeviceKeyStore`] manages a single file on disk that holds the 32-byte
//! device secret generated by [`crate::device_key::DeviceKey::generate`].
//!
//! # Security considerations
//! - The file is written with mode 0o600 on Unix (owner-read/write only).
//! - The file should be placed in a path accessible only to the vault process
//!   (e.g., `$XDG_DATA_HOME/ferreus-vault/device.key` on Linux).
//! - No additional encryption is applied to the device key file; the security
//!   model assumes the device's file-system access controls are intact. For
//!   stronger guarantees, integrate a platform keychain (TPM, Keychain, Credential
//!   Manager) instead of a plain file.

use std::fs;
use std::io;
use std::path::PathBuf;

use crate::device_key::{DeviceKey, DEVICE_KEY_LEN};

/// Manages loading and persisting the device-specific secret key.
pub struct DeviceKeyStore {
    /// Absolute path to the device key file.
    path: PathBuf,
}

impl DeviceKeyStore {
    /// Creates a new [`DeviceKeyStore`] targeting the given file path.
    ///
    /// The path does not need to exist yet; it will be created by
    /// [`DeviceKeyStore::load_or_create`] on first use.
    pub fn new(path: PathBuf) -> Self {
        Self { path }
    }

    /// Loads the device key from disk, or generates and persists a new one.
    ///
    /// ## Behaviour
    /// - If the file at `self.path` already exists, its 32 bytes are read and
    ///   returned as a [`DeviceKey`].
    /// - If the file does not exist, a new key is generated with
    ///   [`DeviceKey::generate`], written to disk, and returned.
    ///
    /// ## Errors
    /// Returns an [`io::Error`] if the file exists but:
    /// - Cannot be read (permission error, I/O failure).
    /// - Contains fewer than [`DEVICE_KEY_LEN`] bytes (truncated or corrupt).
    ///
    /// Also returns an [`io::Error`] if the key file cannot be written.
    ///
    /// ## Platform permissions
    /// On Unix, the key file is created with mode 0o600 so that only the
    /// owning user can read or write it. This requires `std::os::unix::fs`.
    //
    // FIXES APPLIED:
    //   1. `key.copy_from_slice(&bytes..32)` was a syntax error — `..` is not
    //      valid inside an index expression. Changed to `&bytes[..DEVICE_KEY_LEN]`.
    //   2. Added a length check before `copy_from_slice` to return a clear
    //      `InvalidData` error instead of panicking on a short file.
    //   3. Removed the spurious `use anyhow::Ok` import. This shadowed the
    //      standard `Ok` constructor and would cause compile errors once anyhow
    //      is not in scope; the function already returns `std::io::Result`.
    //   4. Added Unix file-permission hardening (0o600) on key file creation.
    pub fn load_or_create(&self) -> io::Result<DeviceKey> {
        if self.path.exists() {
            let bytes = fs::read(&self.path)?;

            // Guard against a truncated or malformed key file.
            if bytes.len() < DEVICE_KEY_LEN {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!(
                        "device key file is too short: expected {} bytes, got {}",
                        DEVICE_KEY_LEN,
                        bytes.len()
                    ),
                ));
            }

            let mut key = [0u8; DEVICE_KEY_LEN];
            // FIX: was `&bytes..32` (syntax error). Correct slice syntax is `&bytes[..N]`.
            key.copy_from_slice(&bytes[..DEVICE_KEY_LEN]);

            Ok(DeviceKey { key })
        } else {
            let key = DeviceKey::generate();

            // Write with restrictive permissions on Unix so the key is not
            // readable by other users on a shared system.
            write_private_file(&self.path, &key.key)?;

            Ok(key)
        }
    }
}

/* ─────────────────────────── Helpers ──────────────────────────────────── */

/// Writes `data` to `path` with mode 0o600 on Unix (owner read/write only).
///
/// On non-Unix platforms, falls back to [`fs::write`] without setting
/// explicit permissions — callers on those platforms should use the OS
/// keychain or equivalent to protect the device key.
fn write_private_file(path: &std::path::Path, data: &[u8]) -> io::Result<()> {
    #[cfg(unix)]
    {
        use std::fs::OpenOptions;
        use std::io::Write;
        use std::os::unix::fs::OpenOptionsExt;

        let mut file = OpenOptions::new()
            .create(true)
            .write(true)
            .truncate(true)
            .mode(0o600) // owner read + write; no group or other access
            .open(path)?;

        file.write_all(data)?;
        file.sync_all()?;
    }

    #[cfg(not(unix))]
    {
        fs::write(path, data)?;
    }

    Ok(())
}

/* ─────────────────────────── Tests ────────────────────────────────────── */

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    /// Verifies that `load_or_create` creates a new key when no file exists,
    /// and that a subsequent call returns the same key bytes.
    #[test]
    fn load_or_create_round_trip() {
        // Use a path inside a temporary directory that does NOT yet exist.
        let dir = tempfile::tempdir().unwrap();
        let key_path = dir.path().join("device.key");

        let store = DeviceKeyStore::new(key_path.clone());

        // First call should generate and persist a new key.
        let key1 = store.load_or_create().expect("initial key creation failed");

        // Second call should load the same key from disk.
        let key2 = store.load_or_create().expect("key reload failed");

        assert_eq!(
            key1.as_bytes(),
            key2.as_bytes(),
            "Reloaded key must match the generated key"
        );
    }

    /// Verifies that a truncated key file returns a clear error rather than
    /// panicking.
    #[test]
    fn truncated_key_file_returns_error() {
        let tmp = NamedTempFile::new().unwrap();
        fs::write(tmp.path(), b"short").unwrap();

        let store = DeviceKeyStore::new(tmp.path().to_path_buf());
        let result = store.load_or_create();

        assert!(
            result.is_err(),
            "A truncated key file must produce an error"
        );
    }
}
