// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Ferreus Vault Contributors
//
// This file is part of Ferreus Vault.
//
// Ferreus Vault is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3 only,
// as published by the Free Software Foundation.
//
// Ferreus Vault is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

//! Vault file persistence layer.
//!
//! # Responsibilities
//! - Atomic vault writes (write-to-temp → fsync → rename).
//! - Encryption orchestration via [`crate::crypto`].
//! - Vault loading, version validation, and decryption.
//!
//! # Security goals
//! - Prevent corruption on crash or power loss via atomic rename.
//! - Avoid plaintext persistence — only ciphertext is written to disk.
//! - Maintain a single, auditable code path for both creation and loading.
//!
//! # KDF contract
//! [`VaultStorage::create_vault`] and [`VaultStorage::load_vault`] both reach
//! the same KDF via [`MasterKey::new_from_password`] and
//! [`MasterKey::from_password_with_salt`] respectively. The parameters live in
//! a single place (`crypto::ARGON2_*` constants) — changing them there updates
//! both paths atomically.
//!
//! # Device binding
//! Both `create_vault` and `load_vault` accept a `device_key` slice that is
//! mixed into the KDF via HKDF-SHA256 inside [`MasterKey`]. Passing `&[]`
//! disables device binding. When a [`crate::device_store::DeviceKeyStore`] is
//! available, callers should supply its key to ensure a stolen vault file
//! cannot be brute-forced on a different machine.

use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::crypto::{EncryptedVault, MasterKey};
use crate::errors::VaultError;
use crate::vault::VaultData;

/// File extension for vault files (includes the leading dot).
pub const VAULT_EXTENSION: &str = ".sark";

/// Handles vault file operations for a single vault path.
pub struct VaultStorage {
    vault_path: PathBuf,
}

impl VaultStorage {
    /// Creates a new [`VaultStorage`] targeting the given path.
    ///
    /// The file does not need to exist yet; it will be created by
    /// [`VaultStorage::create_vault`].
    pub fn new(path: impl AsRef<Path>) -> Self {
        Self {
            vault_path: path.as_ref().to_path_buf(),
        }
    }

    /// Creates and persists a new, empty vault encrypted with `master_password`.
    ///
    /// A fresh random salt is generated by [`MasterKey::new_from_password`],
    /// guaranteeing a unique salt per vault even when the same password is reused.
    /// The `device_key` slice is mixed into the KDF so the derived key is bound
    /// to this specific device; pass `&[]` to disable device binding.
    ///
    /// The vault is written at generation 0. Every subsequent save increments the
    /// generation counter stored in the AEAD AAD, enabling rollback detection.
    ///
    /// # Errors
    /// Propagates serialisation, cryptographic, and I/O errors.
    pub fn create_vault(
        &self,
        master_password: &str,
        vault_data: &VaultData,
        device_key: &[u8],
    ) -> Result<(), VaultError> {
        let master_key = MasterKey::new_from_password(master_password, device_key)?;

        let serialized =
            bincode::serialize(vault_data).map_err(|_| VaultError::SerializationError)?;

        // Generation 0 is reserved for vault creation; VaultManager increments
        // this on every subsequent save via save_generation.
        let encrypted = EncryptedVault::encrypt(&serialized, &master_key, 0)?;

        self.atomic_write(&encrypted.to_bytes()?)
    }

    /// Loads, authenticates, and decrypts a vault file.
    ///
    /// Returns the decrypted [`VaultData`] and the re-derived [`MasterKey`] so
    /// that a subsequent `save_vault` can re-encrypt without prompting for the
    /// password again. The `device_key` must match the value supplied at creation
    /// time; a mismatch produces a different derived key and authentication fails.
    ///
    /// # Errors
    /// - [`VaultError::CorruptedVault`] if the file cannot be parsed or carries
    ///   an unsupported version number.
    /// - [`VaultError::InvalidPassword`] if authentication or decryption fails.
    /// - Propagates I/O errors.
    pub fn load_vault(
        &self,
        master_password: &str,
        device_key: &[u8],
    ) -> Result<(VaultData, MasterKey), VaultError> {
        let vault_bytes = fs::read(&self.vault_path).map_err(VaultError::IoError)?;

        let encrypted_vault =
            EncryptedVault::from_bytes(&vault_bytes).map_err(|_| VaultError::CorruptedVault)?;

        if encrypted_vault.version != EncryptedVault::CURRENT_VERSION {
            return Err(VaultError::CorruptedVault);
        }

        // Re-derive using the salt embedded in the vault header and the same
        // device_key that was supplied at creation time. Any deviation in either
        // input produces a different key and causes the AEAD tag to fail.
        let master_key =
            MasterKey::from_password_with_salt(master_password, &encrypted_vault.salt, device_key)
                .map_err(|_| VaultError::InvalidPassword)?;

        let decrypted_bytes = encrypted_vault
            .decrypt(&master_key)
            .map_err(|_| VaultError::InvalidPassword)?;

        if decrypted_bytes.is_empty() {
            return Err(VaultError::CorruptedVault);
        }

        let vault_data: VaultData =
            bincode::deserialize(&decrypted_bytes).map_err(|_| VaultError::CorruptedVault)?;

        Ok((vault_data, master_key))
    }

    /// Persists a pre-encrypted vault payload atomically.
    ///
    /// Callers are responsible for encrypting the payload before calling this
    /// method. Typically invoked by [`crate::VaultManager::save_vault`].
    pub fn save_vault(&self, encrypted: &[u8]) -> Result<(), VaultError> {
        self.atomic_write(encrypted)
    }

    /// Writes `data` to the vault path atomically using a temp-file + rename.
    ///
    /// ## Write sequence
    /// 1. Write to `<path>.tmp` (mode 0o600 on Unix).
    /// 2. `fsync` the temp file to ensure data reaches durable storage.
    /// 3. Create a timestamped backup of the *existing* vault (if one exists).
    /// 4. `rename` temp → final path (atomic on POSIX, best-effort on Windows).
    /// 5. `fsync` the parent directory to make the rename crash-safe on Linux.
    ///
    /// The backup is created **after** the new data is durably fsynced but
    /// **before** the rename, so a power-loss between steps 3 and 4 leaves both
    /// the old vault and the new temp file intact.
    fn atomic_write(&self, data: &[u8]) -> Result<(), VaultError> {
        let temp_path = self.vault_path.with_extension("tmp");

        let mut options = OpenOptions::new();
        options.create(true).write(true).truncate(true);

        // Restrict permissions to owner-only on Unix before the file is created.
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }

        let mut file = options.open(&temp_path).map_err(VaultError::IoError)?;
        file.write_all(data).map_err(VaultError::IoError)?;
        file.flush().map_err(VaultError::IoError)?;
        // `sync_all` flushes both data and metadata (file size, timestamps) to
        // durable storage. More expensive than `sync_data` but required for a
        // correct crash-recovery guarantee.
        file.sync_all().map_err(VaultError::IoError)?;
        drop(file);

        // Backup the existing vault only after the replacement has been fsynced,
        // so that a crash between here and the rename still leaves a valid backup.
        if self.vault_path.exists() {
            let backup = generate_backup_path(&self.vault_path);
            fs::copy(&self.vault_path, backup).map_err(VaultError::IoError)?;
        }

        // Atomic replace on POSIX; best-effort on Windows.
        fs::rename(&temp_path, &self.vault_path).map_err(VaultError::IoError)?;

        // Flush the directory entry so the rename is durable after a kernel crash.
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            if let Some(parent) = self.vault_path.parent() {
                let dir = OpenOptions::new()
                    .read(true)
                    .custom_flags(libc::O_DIRECTORY)
                    .open(parent)
                    .map_err(VaultError::IoError)?;
                dir.sync_all().map_err(VaultError::IoError)?;
            }
        }

        Ok(())
    }

    /// Returns `true` if the vault file exists at the configured path.
    pub fn vault_exists(&self) -> bool {
        self.vault_path.exists()
    }

    /// Returns the configured vault file path.
    pub fn path(&self) -> &Path {
        &self.vault_path
    }
}

/// Generates a timestamped backup filename adjacent to `base_path`.
///
/// If a file with the generated name already exists, a numeric suffix is
/// appended until a free name is found.
pub fn generate_backup_path(base_path: &Path) -> PathBuf {
    use chrono::Local;

    let timestamp = Local::now().format("%Y%m%d_%H%M%S");
    let base_name = base_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("vault");

    let mut backup_path = base_path.with_file_name(format!(
        "{}_{}_backup{}",
        base_name, timestamp, VAULT_EXTENSION
    ));

    let mut counter: u32 = 1;
    while backup_path.exists() {
        backup_path = base_path.with_file_name(format!(
            "{}_{}_backup_{}{}",
            base_name, timestamp, counter, VAULT_EXTENSION
        ));
        counter += 1;
    }

    backup_path
}

/// Removes the vault file at `path`.
///
/// # Security note
/// This does **not** perform a secure overwrite — secure deletion is
/// unreliable on flash storage (SSD, NVMe) due to wear-levelling.
/// If overwriting is required, zero the file contents before removal.
///
/// # Errors
/// Returns [`VaultError::IoError`] if the file cannot be removed.
pub fn delete_vault_file(path: &Path) -> Result<(), VaultError> {
    fs::remove_file(path).map_err(VaultError::IoError)
}
